AMC.LinesOfCode/Controllers/TotalLinesOfCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AMC.LinesOfCode.Models;
using System.IO;

namespace AMC.LinesOfCode.Controllers
{
    public class TotalLinesOfCodeController : Controller
    {

        
        // GET: TotalLinesOfCode
        public ActionResult Index(TotalLinesOfCodeModel model)

        {
            string rootPath = Server.MapPath("~");

            string path =  rootPath + "Files\\";
            model.FileDirectory = path;
            return View(model);
        }
        
        [HttpPost]
        public ActionResult LinesOfCode(string FileDirectory)
        {
            string path = FileDirectory;
            LineCounterRepository _repository = new LineCounterRepository();
            TotalLinesOfCodeModel model = new TotalLinesOfCodeModel();
            if (String.IsNullOrEmpty(path))
            {
                path = Server.MapPath("~");
            }
            else
            {
                path = @path;
            }
                model.TotalLinesOfCode = _repository.GetCountOfTotalLinesOfCode(path);
                model.TotalFilesProccessed = _repository.GetTotalFilesProcessed(path);
                model.TotalFilesContainCode = _repository.GetTotalNumberOfFilesContainsCode();

            return View(model);
        }
    }
}

AMC.LinesOfCode/Views/TotalLinesOfCode/Index.cshtml
@model AMC.LinesOfCode.Models.TotalLinesOfCodeModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>



@using (Html.BeginForm("LinesOfCode", "TotalLinesOfCode", new { FileDirectory = @Model.FileDirectory },FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken() 
    
    <div class="form-horizontal">
        <h4>Total Lines Of CodeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <fieldset>
                
                <div>
                    <p>
                        File Directory
                        @Html.TextBoxFor(model => model.FileDirectory)
                        <input type="submit" value="CountLines" class="btn btn-primary" />
                    </p>
                </div>
            </fieldset>
            <br />
           
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AMC.LinesOfCode/Views/TotalLinesOfCode/LinesOfCode.cshtml
@model AMC.LinesOfCode.Models.TotalLinesOfCodeModel

@{
    ViewBag.Title = "Total Lines Of Code";
}




@using (Html.BeginForm("LinesOfCode", "TotalLinesOfCode", new { FileDirectory = @Model.FileDirectory }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Total Lines Of Code </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="container">
                <fieldset>

                    <div class="row">
                        <div class="col-md-2">
                            File Directory
                        </div>
                        <div class="col-md-4 padding-0">
                            @Html.TextBoxFor(model => model.FileDirectory, new { style="width:500px;"})
                            </diV>
                        <div class="col-md-6 padding-0">
                            <input type="submit" value="CountLines" class="btn btn-primary" />
                        </div>
                      
                    </div>
                </fieldset>
                <br />
                <fieldset>
    @if (Model != null)
    {
    <div class="row">
    <div class="col-md-2 padding-0">
        @Html.LabelFor(model => model.TotalFilesProccessed, "Total Files Proccessed")
    </div>
    <div class="col-md-2 padding-0">
         @Html.TextBoxFor(model => model.TotalFilesProccessed)
    </div>
    </div>
    <div class="row">
    <div class="col-md-2 padding-0">
         @Html.LabelFor(model => model.TotalFilesContainCode, "Total Files With Code")
    </div>
    <div class="col-md-2 padding-0">
            @Html.TextBoxFor(model => model.TotalFilesContainCode)
    </div>
    </div>
    <div class="row">
    <div class="col-md-2 padding-0">
         @Html.LabelFor(model => model.TotalLinesOfCode, "Total Lines Of Code")
    </div>
    <div class="col-md-2 padding-0">
        @Html.TextBoxFor(model => model.TotalLinesOfCode)
    </div>
    </div>


}

</fieldset>
            </div>

            </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}